#!/bin/bash

TYPE="${1:-dens}"
DATA_DIR="${2:-output}"
PAUSE="${3:-0.1}"

echo "TYPE=$TYPE DATA_DIR=$DATA_DIR PAUSE=$PAUSE"

case $TYPE in 

    dens)
        python3 "scripts/plot_density.py" "$DATA_DIR" "$PAUSE"
    ;;

    spec)
        python3 "scripts/plot_spectrum.py" "$DATA_DIR" "$PAUSE"
    ;;

esac

